OldScanner/Models/ErrorViewModel.cs
using System;

namespace OldScanner.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OldScanner/Models/LastMinute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OldScanner.Models
{
    public class LastMinute
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public string Time { get; set; }
        public string Event { get; set; }
        public string SubEvent { get; set; }
        public string One { get; set; }
        public string X { get; set; }
        public string Two { get; set; }
        public string Over { get; set; }
        public string Under { get; set; }
        public string CG { get; set; }
        public string NG { get; set; }
    }
}

OldScanner/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OldScanner.Models;

namespace OldScanner.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OldScanner/Controllers/OldScannerController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading;
using Microsoft.AspNetCore.Mvc;
using OldScanner.Models;
using OldScanner.Services;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace OldScanner.Controllers
{
    public class OldScannerController : Controller
    {
        private string url = "https://www.planetwin365.it/it/scommesse";

        private IBrowserDriverRepository _browserDriverRepository;
        private ChromeDriver _chromeDriver;

        ILastMinuteRepository _lastMinuteRepository;
        public OldScannerController(IBrowserDriverRepository browserDriverRepository, ILastMinuteRepository lastMinuteRepository)
        {
            _browserDriverRepository = browserDriverRepository;
            _chromeDriver = browserDriverRepository.GetChromeDriver();
            _chromeDriver.Navigate().GoToUrl(url);
            _lastMinuteRepository = lastMinuteRepository;
        }

        public IActionResult GetLastMinute()
        {

            IWebElement rootItem = _chromeDriver.FindElementByCssSelector("#NESportCnt > div.itemSport > div.items");
            ReadOnlyCollection<IWebElement> childItems = rootItem.FindElements(By.ClassName("col7"));

            List<LastMinute> lastMinutesList = new List<LastMinute>();

            foreach (var childItem in childItems)
            {
                LastMinute lastMinute = new LastMinute();

                string data = childItem.FindElement(By.ClassName("data")).Text;
                string time = childItem.FindElement(By.ClassName("time")).Text;
                string events = childItem.FindElement(By.ClassName("event")).Text;
                string subEvent = childItem.FindElement(By.ClassName("subevent")).Text;
                ReadOnlyCollection<IWebElement> odsItems = childItem.FindElements(By.TagName("a"));

                lastMinute.Data = data;
                lastMinute.Time = time;
                lastMinute.Event = events;
                lastMinute.SubEvent = subEvent;

                lastMinute.One = odsItems[1].Text;
                lastMinute.X = odsItems[2].Text;
                lastMinute.Two = odsItems[3].Text;
                lastMinute.Over = odsItems[4].Text;
                lastMinute.Under = odsItems[5].Text;
                lastMinute.CG = odsItems[6].Text;
                lastMinute.NG = odsItems[7].Text;

                lastMinutesList.Add(lastMinute);

                _lastMinuteRepository.AddLastMinute(lastMinute);
            }

            _chromeDriver.Quit();

            return View(lastMinutesList);
        }
    }
}

OldScanner/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OldScanner/Views/OldScanner/GetLastMinute.cshtml
@model IEnumerable<OldScanner.Models.LastMinute>

@{
    ViewData["Title"] = "GetLastMinute";
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubEvent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.One)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.X)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Two)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Over)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Under)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NG)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Event)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubEvent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.One)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.X)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Two)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Over)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Under)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NG)
            </td>
        </tr>
}
    </tbody>
</table>

OldScanner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OldScanner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="OldScanner" asp-action="GetLastMinute">OldScanner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OldScanner" asp-action="GetLastMinute">LAST MINUTE</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - OldScanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>